// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace AspNetCore8Day4.Models;

public partial class ContosoUniversityContext : DbContext
{
    public override int SaveChanges()
    {
        var entries = ChangeTracker
            .Entries()
            .Where(e => e.State == EntityState.Modified);

        foreach (var entry in entries)
        {
            Console.WriteLine("Entity Name: {0}", entry.Entity.GetType().FullName);
            Console.WriteLine("Status: {0}", entry.State);

            entry.OriginalValues.GetValue<DateTime>("ModifiedOn");

            entry.CurrentValues.SetValues(new { ModifiedOn = DateTime.Now });
        }

        return base.SaveChanges();
    }
}