// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetCore8Day4.Models;

public partial class Course
{
    /// <summary>
    /// Unique identifier for the course.
    /// </summary>
    public int CourseId { get; set; }

    /// <summary>
    /// The title of the course.
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// The number of credits assigned to the course.
    /// </summary>
    public int Credits { get; set; }

    /// <summary>
    /// The ID of the department to which the course belongs.
    /// </summary>
    public int DepartmentId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Enrollment> Enrollments { get; set; } = new List<Enrollment>();

    public virtual ICollection<Person> Instructors { get; set; } = new List<Person>();
}