// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetCore8Day4.Models;

public partial class MyDeptCourse
{
    public int CourseId { get; set; }

    public string Title { get; set; }

    public int Credits { get; set; }

    public string DepartmentName { get; set; }
}