// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetCore8Day4.Models;

public partial class VwDepartmentCourseCount
{
    public int DepartmentId { get; set; }

    public string Name { get; set; }

    public int? CourseCount { get; set; }
}