@HostDomain = http://localhost:5076

GET {{HostDomain}}/weatherforecast?q=Git
Accept: application/json
X-Database-Name: ContosoUniversity

###


GET {{HostDomain}}/WeatherForecast/MyDeptCourses?q=Git
Accept: application/json


###


GET {{HostDomain}}/WeatherForecast/GetMyDeptCourses?q=Git
Accept: application/json

###


GET {{HostDomain}}/WeatherForecast/GetMyDeptCourses2?q=Git
Accept: application/json

###


GET {{HostDomain}}/WeatherForecast/GetCourseWithPerson
Accept: application/json

###


GET {{HostDomain}}/api/Courses?pageIndex=4&pageSize=2
Accept: application/json

###


GET {{HostDomain}}/api/Courses/14
Accept: application/json

###

PUT {{HostDomain}}/api/Courses/1
Content-Type: application/json
Accept: application/json

{
  "courseId": 1,
  "title": "Entity Framework 6 開發實戰 456",
  "credits": 5
}

###

POST {{HostDomain}}/api/courses
Content-Type: application/json

{
  "title": "ASP.NET Core 8 開發實戰",
  "credits": 5
}

###

GET {{HostDomain}}/api/Departments
Accept: application/json

###

GET {{HostDomain}}/api/Departments/1
Accept: application/json

###

GET {{HostDomain}}/api/Departments/1/Courses
Accept: application/json

###


GET {{HostDomain}}/api/Courses
Accept: application/json

###

POST {{HostDomain}}/api/Courses/BatchUpdateCredits
Accept: application/json

###
