@AspNetCore8Day4_HostAddress = http://localhost:5076

GET {{AspNetCore8Day4_HostAddress}}/weatherforecast?q=1;%20DROP%20TABLE%20Course
Accept: application/json
X-Database-Name: ContosoUniversity

###


GET {{AspNetCore8Day4_HostAddress}}/WeatherForecast/MyDeptCourses?q=Git
Accept: application/json


###


GET {{AspNetCore8Day4_HostAddress}}/WeatherForecast/GetMyDeptCourses?q=Git
Accept: application/json

###


GET {{AspNetCore8Day4_HostAddress}}/WeatherForecast/GetMyDeptCourses2?q=Git
Accept: application/json

###


GET {{AspNetCore8Day4_HostAddress}}/WeatherForecast/GetCourseWithPerson
Accept: application/json
